### ISSUE TITLE
Code Format

### ISSUE THREAD

**Issue by jamierocks** [EthanRiley/PastPapers#6]
Currently the code is a mix between 2 spaces and tabs.

I propose we use either 4 spaces, or tabs.

**Comment by UnkDevE** [comment]
any way of not doing this manually? atom seems to use(tabs) and also vim does too(i think).

**Comment by UnkDevE** [comment]
or vim is using 2 spaces as tabs.

**Comment by jamierocks** [comment]
IntelliJ can reformat the entire project, I'm happy to do this when we have decided on which format to use.

**Comment by UnkDevE** [comment]
hmm, which do you perfer?

**Comment by jamierocks** [comment]
I prefer 4 spaces, you always know how big their going to look that way.

**Comment by UnkDevE** [comment]
4 spaces seems like a better idea but atom and vim uses tabs.

**Comment by UnkDevE** [comment]
4 spaces it is then.
